import { Section, SECTION_TYPES } from '@/lib/types';

const now = '2026-09-05T00:00:00.000Z';

export const sampleSections: Section[] = [
  {
    id: 'sample-hero',
    order_index: 0,
    visible: true,
    type: SECTION_TYPES.HERO,
    title_en: 'Dhruvil Hirenbhai Patel',
    title_gu: 'ધ્રુવિલ હિરેનભાઈ પટેલ',
    content_en: 'AI Engineer based in Pune with a family-oriented background.',
    content_gu: 'પુણેમાં સ્થિત AI Engineer, પરિવારને મહત્વ આપતી પૃષ્ઠભૂમિ સાથે.',
    created_at: now,
    updated_at: now,
  },
  {
    id: 'sample-about',
    order_index: 1,
    visible: true,
    type: SECTION_TYPES.ABOUT,
    title_en: 'About',
    title_gu: 'વિશે',
    content_en: JSON.stringify({
      'Full Name': 'Dhruvil Hirenbhai Patel',
      'Date of Birth': '07 June 2001',
      'Place of Birth': 'Surat',
      Age: '25',
      Height: "5'11\"",
      Weight: '85 KGs',
      'Blood Group': 'O+',
      'Caste / Subcaste': 'Hindu Lal Chuda Kadva Patidar',
      Rashi: 'Dhanu / Sagittarius',
      'Current City': 'Pune',
    }),
    content_gu: JSON.stringify({
      'Full Name': 'ધ્રુવિલ હિરેનભાઈ પટેલ',
      'Date of Birth': '07 June 2001',
      'Place of Birth': 'સુરત',
      Age: '25',
      Height: "5'11\"",
      Weight: '85 KGs',
      'Blood Group': 'O+',
      'Caste / Subcaste': 'હિન્દુ લાલ ચુડા કડવા પાટીદાર',
      Rashi: 'ધનુ / Sagittarius',
      'Current City': 'પુણે',
      _key_labels: {
        'Full Name': 'પૂર્ણ નામ',
        'Date of Birth': 'જન્મ તારીખ',
        'Place of Birth': 'જન્મ સ્થળ',
        Age: 'ઉંમર',
        Height: 'ઊંચાઈ',
        Weight: 'વજન',
        'Blood Group': 'બ્લડ ગ્રુપ',
        'Caste / Subcaste': 'જાતિ / પેટા જાતિ',
        Rashi: 'રાશિ',
        'Current City': 'વર્તમાન શહેર',
      },
    }),
    created_at: now,
    updated_at: now,
  },
  {
    id: 'sample-education',
    order_index: 2,
    visible: true,
    type: SECTION_TYPES.CAREER,
    title_en: 'Education & Career',
    title_gu: 'શિક્ષણ અને કારકિર્દી',
    content_en: JSON.stringify({
      'Highest Qualification': 'B.Tech Information Technology & Engineering (IT&E)',
      Field: 'Artificial Intelligence (AI)',
      University: 'P. P Savani University',
      'Year of Graduation': '2025',
      'Current Occupation': 'AI Engineer',
      Company: 'EY GDS',
      'Industry / Sector': 'Software',
      'Work Location': 'Pune',
      _is_gold_medalist: true,
    }),
    content_gu: JSON.stringify({
      'Highest Qualification': 'B.Tech Information Technology & Engineering (IT&E)',
      Field: 'Artificial Intelligence (AI)',
      University: 'P. P Savani University',
      'Year of Graduation': '2025',
      'Current Occupation': 'AI Engineer',
      Company: 'EY GDS',
      'Industry / Sector': 'Software',
      'Work Location': 'પુણે',
      _is_gold_medalist: true,
      _key_labels: {
        'Highest Qualification': 'સર્વોચ્ચ લાયકાત',
        Field: 'ક્ષેત્ર',
        University: 'યુનિવર્સિટી',
        'Year of Graduation': 'ગ્રેજ્યુએશન વર્ષ',
        'Current Occupation': 'વર્તમાન વ્યવસાય',
        Company: 'કંપની',
        'Industry / Sector': 'ઇન્ડસ્ટ્રી / સેક્ટર',
        'Work Location': 'કામનું સ્થળ',
      },
    }),
    created_at: now,
    updated_at: now,
  },
  {
    id: 'sample-family',
    order_index: 3,
    visible: true,
    type: SECTION_TYPES.FAMILY,
    title_en: 'Family Details',
    title_gu: 'પારિવારિક વિગતો',
    content_en: JSON.stringify({
      "Father's Name": 'Hirenbhai Rameshbhai Patel',
      "Father's Occupation": 'Diamond Business & Agriculture',
      "Mother's Name": 'Darshanaben Hirenbhai Patel',
      "Mother's Occupation": 'Housewife',
      "Sister's Name": 'Dhruvi Hirenbhai Patel',
      "Sister's Occupation": "Ongoing Bachelor's in Computer Engineering",
      'Family Type': 'Nuclear',
      'Native Place': 'Mulad',
      'Late Grandfather': 'Bharatbhai Dayabhai Patel',
      'Late Grandmother': 'Geetaben Bharatbhai Patel',
      'Maternal Uncle 1 (Mama)': 'Hiralbhai Bharatbhai Patel (Athwa Umra)',
      'Maternal Uncle 2 (Mama)': 'Hetalbhai Bharatbhai Patel (Kemraj Char Rasta)',
    }),
    content_gu: JSON.stringify({
      "Father's Name": 'હિરેનભાઈ રમેશભાઈ પટેલ',
      "Father's Occupation": 'ડાયમંડ બિઝનેસ અને એગ્રીકલ્ચર',
      "Mother's Name": 'દર્શનાબેન હિરેનભાઈ પટેલ',
      "Mother's Occupation": 'ગૃહિણી',
      "Sister's Name": 'ધ્રુવી હિરેનભાઈ પટેલ',
      "Sister's Occupation": "Computer Engineering માં ચાલુ Bachelor's",
      'Family Type': 'ન્યુક્લિયર',
      'Native Place': 'મુલાડ',
      'Late Grandfather': 'ભારતભાઈ દયાભાઈ પટેલ',
      'Late Grandmother': 'ગીતાબેન ભારતભાઈ પટેલ',
      'Maternal Uncle 1 (Mama)': 'હિરલભાઈ ભારતભાઈ પટેલ (અઠવા ઉમરા)',
      'Maternal Uncle 2 (Mama)': 'હેતલભાઈ ભારતભાઈ પટેલ (કેમરાજ ચાર રસ્તા)',
      _key_labels: {
        "Father's Name": 'પિતાનું નામ',
        "Father's Occupation": 'પિતાનો વ્યવસાય',
        "Mother's Name": 'માતાનું નામ',
        "Mother's Occupation": 'માતાનો વ્યવસાય',
        "Sister's Name": 'બહેનનું નામ',
        "Sister's Occupation": 'બહેનનું અભ્યાસ',
        'Family Type': 'પરિવારનો પ્રકાર',
        'Native Place': 'વતન',
        'Late Grandfather': 'સ્વ. દાદા',
        'Late Grandmother': 'સ્વ. દાદી',
        'Maternal Uncle 1 (Mama)': 'મામા 1',
        'Maternal Uncle 2 (Mama)': 'મામા 2',
      },
    }),
    created_at: now,
    updated_at: now,
  },
  {
    id: 'sample-contact',
    order_index: 4,
    visible: true,
    type: SECTION_TYPES.CONTACT,
    title_en: 'Contact',
    title_gu: 'સંપર્ક',
    content_en: JSON.stringify({
      email: 'Dhruvil7694@gmail.com',
    }),
    content_gu: JSON.stringify({
      email: 'Dhruvil7694@gmail.com',
    }),
    created_at: now,
    updated_at: now,
  },
];
